# Generated by Django 4.1.2 on 2023-07-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('familyName', models.CharField(blank=True, max_length=30)),
                ('scientificName', models.CharField(blank=True, max_length=30)),
                ('englishName', models.CharField(blank=True, max_length=30)),
                ('nickName', models.CharField(blank=True, max_length=30)),
                ('level', models.PositiveIntegerField(blank=True)),
                ('startMonth', models.PositiveIntegerField(blank=True)),
                ('endMonth', models.PositiveIntegerField(blank=True)),
                ('season', models.PositiveIntegerField(blank=True)),
                ('habitat', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='uploads/')),
                ('photoby', models.TextField(blank=True)),
            ],
        ),
    ]
