# Generated by Django 4.1.2 on 2023-07-16 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BirdModel',
            fields=[
                ('id', models.PositiveIntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30, unique=True)),
                ('familyName', models.CharField(max_length=30, null=True)),
                ('scientificName', models.CharField(max_length=30, null=True)),
                ('englishName', models.CharField(max_length=30, null=True)),
                ('nickName', models.CharField(max_length=30, null=True)),
                ('level', models.PositiveIntegerField(null=True)),
                ('startMonth', models.PositiveIntegerField(null=True)),
                ('endMonth', models.PositiveIntegerField(null=True)),
                ('season', models.PositiveIntegerField(null=True)),
                ('habitat', models.CharField(max_length=30, null=True)),
                ('description', models.TextField(null=True)),
                ('image', models.ImageField(null=True, upload_to='image/')),
                ('photoby', models.CharField(max_length=30)),
            ],
        ),
    ]
