# Generated by Django 4.1.2 on 2023-01-04 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pltem', models.IntegerField()),
                ('psupplier', models.CharField(max_length=30)),
                ('pname', models.CharField(max_length=30)),
                ('pimage', models.CharField(max_length=40)),
                ('pquantity', models.IntegerField()),
                ('pprice', models.IntegerField()),
                ('pdescription', models.CharField(max_length=30)),
            ],
        ),
    ]
