# Generated by Django 4.1.2 on 2023-01-07 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productmodel',
            name='plocal',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
