# Generated by Django 4.1.2 on 2023-01-07 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_productmodel_plocal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productmodel',
            name='plocal',
        ),
        migrations.AddField(
            model_name='productmodel',
            name='pclass',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
