# Generated by Django 4.1.2 on 2023-07-13 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_alter_birdmodel_endmonth_alter_birdmodel_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='birdmodel',
            name='photo',
            field=models.ImageField(null=True, upload_to='photos'),
        ),
    ]
