# Generated by Django 4.1.2 on 2023-01-08 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_remove_productmodel_plocal_productmodel_pclass'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pltem',
            field=models.IntegerField(max_length=30),
        ),
    ]
