# Generated by Django 4.1.2 on 2023-01-08 03:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0004_alter_productmodel_pltem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pprice',
            field=models.IntegerField(max_length=30),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pquantity',
            field=models.IntegerField(max_length=30),
        ),
    ]
