# Generated by Django 4.1.2 on 2023-01-14 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0007_alter_productmodel_pprice_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pimage',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='pltem',
            field=models.IntegerField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='productmodel',
            name='psupplier',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
