# Generated by Django 4.1.2 on 2023-01-15 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_alter_productmodel_pimage_alter_productmodel_pltem_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmodel',
            name='pltem',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
