# Generated by Django 4.1.2 on 2023-03-02 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0010_alter_productmodel_pprice_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pltem', models.CharField(max_length=30, null=True)),
                ('pclass', models.CharField(max_length=50)),
                ('psupplier', models.CharField(max_length=30, null=True)),
                ('pname', models.CharField(max_length=30)),
                ('pimage', models.CharField(max_length=40, null=True)),
                ('pquantity', models.IntegerField()),
                ('pprice', models.IntegerField()),
                ('pdescription', models.CharField(max_length=30)),
            ],
        ),
    ]
