# Generated by Django 4.1.2 on 2023-03-02 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0011_customer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='pclass',
            new_name='cclass',
        ),
        migrations.RenameField(
            model_name='customer',
            old_name='pltem',
            new_name='cname',
        ),
    ]
